version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /front-end
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 20s
      retries: 5
  backend:
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /back-end
    command: dev
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=senhaDoDB
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 20s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: deliveryDb
    platform: linux/x86_64
    ports:
      - 3005:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
    restart: "always"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
    cap_add:
      - SYS_NICE
